name: Validate Windows plugin host API

on:
  workflow_dispatch:

jobs:
  build_windows_x64:
    name: Build Windows x64
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: windows-latest
      arch: x64
      build-deps-only: false
      force-build: true
    secrets: inherit

  unit_tests_windows_x64:
    name: Windows x64
    needs: build_windows_x64
    if: ${{ !cancelled() && success() }}
    uses: ./.github/workflows/unit_tests.yml
    with:
      os: windows-latest
      artifact: ${{ github.sha }}-tests-windows-x64
